# Generated by Django 5.0.1 on 2024-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
    ]
