# Generated by Django 5.0.1 on 2024-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key='true', serialize=False)),
                ('mobile', models.BigIntegerField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
